name: Java CI

on:
  push:
    branches: [ main, claude/** ]
    paths:
      - 'java/**'
      - '.github/workflows/java-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'java/**'

jobs:
  test:
    name: Test Java Examples
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Check Java version
      run: |
        java -version
        mvn --version

    - name: Build Java examples with Maven
      run: |
        for dir in java/examples/*/; do
          if [ -f "$dir/pom.xml" ]; then
            echo "Building $dir"
            cd "$dir"
            mvn clean compile
            cd - > /dev/null
          fi
        done

    - name: Run Java tests
      run: |
        for dir in java/examples/*/; do
          if [ -f "$dir/pom.xml" ]; then
            echo "Testing $dir"
            cd "$dir"
            mvn test
            cd - > /dev/null
          fi
        done

    - name: Check code style
      run: |
        for dir in java/examples/*/; do
          if [ -f "$dir/pom.xml" ]; then
            echo "Checking style for $dir"
            cd "$dir"
            mvn checkstyle:check || true
            cd - > /dev/null
          fi
        done

    - name: Generate test coverage
      run: |
        for dir in java/examples/*/; do
          if [ -f "$dir/pom.xml" ]; then
            echo "Generating coverage for $dir"
            cd "$dir"
            mvn jacoco:report || true
            cd - > /dev/null
          fi
        done
